#!/bin/bash
# shellcheck disable=2038,2002,2129


paraphrasingPATH="/data/projects/py/pdfgpt/src"
len=38
Exclude="p1.md|39.md|40.md|41.md|44.md|p4.md"
readarray -t mdbook < <( \
  diff -q --recursive "$paraphrasingPATH" ./src |
  grep '\.md$'|
  grep "$paraphrasingPATH:" |
  grep -vE "$Exclude" |
  sed -E 's#^.{'$len'}##' )

for file in "${mdbook[@]}";do
  echo "$file"
  cp "$paraphrasingPATH/$file" ./src

  echo "- [${file%.md}](./$file)" >> ./src/SUMMARY.md
  echo "- [${file%.md}](./$file)" >> ./src/README.md
  git add "./src/$file"
done

if git status -s | awk '{print $1}' | grep A; then
  git commit -m 'init' src/ && git push
else
  echo "no file to commit/push"
fi


