#!/bin/bash
# shellcheck disable=2038,2002,2129


paraphrasingPATH="/data/projects/py/pdfgpt/src"
len=38
Exclude="p1.md|39.md|40.md|41.md|44.md|p4.md"
readarray -t mdbook < <( \
  diff -q --recursive "$paraphrasingPATH" ./src |
  grep '\.md$'|
  grep "$paraphrasingPATH:" |
  grep -vE "$Exclude" |
  sed -E 's#^.{'$len'}##' )

for file in "${mdbook[@]}";do
  echo "$file"
  mv "$paraphrasingPATH/$file" ./src

  echo "- [${file%.md}](./$file)" >> ./src/SUMMARY.md
  # echo "- [${file%.md}](./$file)" >> ./src/README.md
  git add "./src/$file"
done

if git status -s | awk '{print $1}' | grep A >/dev/null; then
  echo "git start" && \
    git commit -m 'init' src/ >/dev/null 2>&1 && \
    git push >/dev/null 2>&1 && \
    echo "git Done"
else
  echo "no file to commit/push"
fi


